spring:
  application:
    name: life-line-back-end
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://comic-vulture-37.clerk.accounts.dev
  datasource:
    url: jdbc:postgresql://localhost:5432/whatdoidodb
    username: aki
    password: aki
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: create-drop
      defer-datasource-initialization: true
    sql:
      init:
        platform: postgresql
        mode: always
