spring:
  application:
    name: what-do-i-do-backend
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_PROVIDER_URI}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        cachePrepStmts: false

  jpa:
    hibernate:
      ddl-auto: none #create or create-drop
    defer-datasource-initialization: false #true for data seeding

  sql:
    init:
      platform: postgresql
      mode: never #always for data seeding
